using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace StoreManagement.Orders;

public class CreateOrderDto
{
    /*
     * OrderNumber will be generated by backend.
     * Frontend should not send it.
     */

    [Required]
    [MaxLength(OrderConsts.MaxCustomerNameLength)]
    public string CustomerName { get; set; } = string.Empty;
    
    [Required]
    [MaxLength(OrderConsts.MaxCustomerAddressLength)]
    public string CustomerAddress { get; set; } = string.Empty;
    
    [MaxLength(OrderConsts.MaxCustomerPhoneLength)]
    public string? CustomerPhone { get; set; }

    [MaxLength(OrderConsts.MaxNoteLength)]
    public string? Note { get; set; }

    [Required]
    public List<CreateOrderItemDto> Items { get; set; } = new();
}